### ISSUE TITLE
Web facing DB UI

### ISSUE THREAD

**Issue by Zayelion** [SalvationDevelopment/YGOPro-Salvation-Server#287]
Create a web facing DB manipulation UI for `cards.cdb` based on the DevPro Card Editor.

**Comment by StormWulf** [comment]
As requested, screenshot reference for the DevPro Card Manager

![DevPro Card Manager](https://i.imgur.com/eZAJIHy.png)

**Comment by Zayelion** [comment]
Could I get the other tabs and the drop downs of the File/Tools/About also?

**Comment by StormWulf** [comment]
Post edited

**Comment by Zayelion** [comment]
In progress

**Comment by StormWulf** [comment]
When the `alias` box is empty, a `0` should print in the column rather than a blank space. Leaving it blank will brick the database, apparently.

For quotation marks in a card's description, the SQL editor currently prints `\` next to the quotation marks, but it should be printing additional quotation marks so that the database will accept the insert queries.

**Comment by Zayelion** [comment]
Finished up key features we dont prefer doing by hand. Should I add picture and script conversions?

**Comment by StormWulf** [comment]
Yes please

**Comment by Zayelion** [comment]
done, its limited to the launcher but can go into a bug checking phase now.
